name: stall_noodle
description: The way you can add location you favourite noodle place

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  #state management
  provider: ^4.3.3
  #databse
  sqflite: ^1.3.2+3
  #toast alert
  fluttertoast: ^7.1.6
  #path provider
  path_provider: ^1.6.27
  #shared preferences
  shared_preferences: ^0.5.12+4
  #slidable widget
  flutter_slidable: "^0.4.7"
  #Google maps
  google_maps_flutter: ^1.2.0
  google_maps_webservice: ^0.0.18
  flutter_google_places: ^0.2.6
  #http
  http: ^0.12.2
  #JSON Serialization
  json_serializable: ^3.5.1
  #Current Location
  geolocator: ^6.2.1
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  build_runner: ^1.11.1


# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IBMPlexSansRegular
      fonts:
        - asset: assets/fonts/ibm_plex_sans_regular.ttf

    - family: IBMPlexSansBold
      fonts:
        - asset: assets/fonts/ibm_plex_sans_bold.ttf

    - family: IBMPlexSansMedium
      fonts:
        - asset: assets/fonts/ibm_plex_sans_medium.ttf

    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/roboto_regular.ttf

    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/open_sans_semi_bold.ttf