name: stall_noodle
description: The way you can add location you favourite noodle place

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  sqflite: ^1.3.2+3
  fluttertoast: ^7.1.6
  path_provider: ^1.6.27
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IBMPlexSansRegular
      fonts:
        - asset: assets/fonts/ibm_plex_sans_regular.ttf

    - family: IBMPlexSansBold
      fonts:
        - asset: assets/fonts/ibm_plex_sans_bold.ttf

    - family: IBMPlexSansMedium
      fonts:
        - asset: assets/fonts/ibm_plex_sans_medium.ttf

    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/roboto_regular.ttf

    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/open_sans_semi_bold.ttf